export const darkTheme = {
  backgroundColor: "#292C33",
  backgroundLightGrayColor: "#292C33",
  backgroundGrayColor: "#292C33",
  headerBackgroundColor: "#292C33",
  containerColor: "#343538",
  commentContainerColor: "#343538",
  commentColor: "#fff",
  toggleBtnTextColor: "#fff",
  containerGrayColor: "#E2ECF0",
  headerColor: "#727272",
  headerHoverColor: "#fff",
  textColor: "#fff",
  textGrayColor: "#fff",
  svelteOrangeColor: "#ed702d;",
  userRankOddBoxColor: "#343538",
};
export const lightTheme = {
  backgroundColor: "white",
  backgroundLightGrayColor: "#efefef",
  backgroundGrayColor: "#F5F5F5",
  headerBackgroundColor: "#ee702c",
  containerColor: "#fff",
  containerGrayColor: "#fff",
  commentContainerColor: "#efefef",
  toggleBtnTextColor: "b7b7b7",
  commentColor: "#3f3f3f",
  headerColor: "#ee702c#",
  headerHoverColor: "#727272",
  textColor: "black",
  textGrayColor: "#202020",
  svelteOrangeColor: "#ed702d;",
  userRankOddBoxColor: "#fff",
};
